name: Scan AI Repos with OpenGrep

on:
  workflow_dispatch:

jobs:
  opengrep-scan:
    name: Run Opengrep
    runs-on: self-hosted

    steps:
      - name: Run OpenGrep on repo 1
        run: |
         C:\Users\DELL\Desktop\Opengrep-rules\opengrep_windows_x86.exe scan --json -o C:\Users\DELL\Desktop\Opengrep-rules\output\repo1-results.json -f C:\Users\DELL\Desktop\Opengrep-rules\detection-rule-for-azure-ai-usage.yml C:\Users\DELL\Desktop\Opengrep-rules\repos\azure-openai-samples

      - name: Print findings
        run: |
          type C:\Users\DELL\Desktop\Opengrep-rules\output\repo-results.json
