name: Scan Repository with OpenGrep Rules

on:
  workflow_dispatch:

jobs:
  opengrep-scan:
    name: Run Opengrep Security Scan
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: |
          if (!(Test-Path "C:\Users\DELL\Desktop\Opengrep-rules\output")) {
            New-Item -ItemType Directory -Path "C:\Users\DELL\Desktop\Opengrep-rules\output" -Force
          }

      - name: Run OpenGrep with .opengrep rules
        run: |
          C:\Users\DELL\Desktop\Opengrep-rules\opengrep_windows_x86.exe scan --json -o C:\Users\DELL\Desktop\Opengrep-rules\output\scan-results.json -f .opengrep\ .

      - name: Display scan results
        run: |
          if (Test-Path "C:\Users\DELL\Desktop\Opengrep-rules\output\scan-results.json") {
            Write-Host "=== OpenGrep Scan Results ==="
            Get-Content "C:\Users\DELL\Desktop\Opengrep-rules\output\scan-results.json" | ConvertFrom-Json | ConvertTo-Json -Depth 10
          } else {
            Write-Host "No scan results file found"
          }

